### ISSUE TITLE
centos不可用

### ISSUE THREAD

**Issue by dfmjndm** [RSRH-Rs/webscreenshot#2]
linux环境，网页截图+网站会显示超时
然后发送图片的那个函数，我把路径已经改成linux下的路径了，最终bot发出来的是文字”[CQ:image,file=/hoshino/modules/Hoshino-plugin-webscreenshot/temp/1681955810.png]“
所以这个插件使用的nonebot版本是？

另外查看了一下目录，1681955810.png这张图片根本没有输出

**Comment by RSRH-Rs** [comment]
> linux环境，网页截图+网站会显示超时
> 然后发送图片的那个函数，我把路径已经改成linux下的路径了，最终bot发出来的是文字”[CQ:image,file=/hoshino/modules/Hoshino-plugin-webscreenshot/temp/1681955810.png]“
> 所以这个插件使用的nonebot版本是？
> 
> 另外查看了一下目录，1681955810.png这张图片根本没有输出

emm，nb版本是1.8也就是hoshino的依赖，图片发不出去是因为没有加协议，按理来说MessageSegment.image是可以直接把图片转换成cq码的。另外超时的网站是什么，加我qq1171881690细说

**Comment by dfmjndm** [comment]
![O_N529)W_4CZYCID54F)KUF](https://user-images.githubusercontent.com/57401901/234903751-97963040-4d72-4895-833d-46b950e33f23.png)
使用指令：“网页截图 www.baidu.com”
